use crossterm::{
    ExecutableCommand,
    style::{Color, ResetColor, SetForegroundColor},
};
use std::io::{stdin, stdout, Read};

#[derive(PartialEq, Debug)]
pub enum PrintCommand {
    AICall,
    UnitTest,
    Issue,
}

impl PrintCommand {
    pub fn print_agent_message(&self, agent_pos: &str, agent_statement: &str) {
        let mut stdout: std::io::Stdout = stdout();

        // Decide on the print colour
        let statement_colour: Color = match self {
            Self::AICall => Color::Cyan,
            Self::UnitTest => Color::Magenta,
            Self::Issue => Color::Red,
        };

        // Print the agent statement in a specific color
        stdout
            .execute(SetForegroundColor(Color::DarkYellow))
            .unwrap();
        print!("Agent: {}: ", agent_pos);

        // Make selected color
        stdout
            .execute(SetForegroundColor(statement_colour))
            .unwrap();
        println!("{}", agent_statement);

        // Reset Color
        stdout.execute(ResetColor).unwrap();
    }
}

pub fn get_user_response(question: &str) -> String {
    let mut stdout: std::io::Stdout = stdout();

    //Print the question in a specific color
    stdout.execute(SetForegroundColor(Color::Blue)).unwrap();
    println!("");
    println!("{}", question);

    //Reset Color
    stdout.execute(ResetColor).unwrap();

    //Read user input
    let mut user_response: String = String::new();
    stdin()
        .read_line(&mut user_response)
        .expect("Failed to read response");

    //Trim whitespace and return
    return user_response.trim().to_string();
}

pub fn confirm_safe_code() -> bool {
    let mut stdout: std::io::Stdout = stdout();
    loop {
        //Print the question in specified order
        stdout.execute(SetForegroundColor(Color::Blue)).unwrap();
        println!("");
        print!("WARNING! You are about to run code generated by AI.");
        println!("Review your code and confirm you wish to continue.");

        //Reset Color
        stdout.execute(ResetColor).unwrap();

        //Present Options with different colors
        stdout.execute(SetForegroundColor(Color::Green)).unwrap();
        println!("[1] All Good");
        stdout.execute(SetForegroundColor(Color::DarkRed)).unwrap();
        println!("[2] No, stop the project");

        //Reset Color
        stdout.execute(ResetColor).unwrap();

        //Read User Input
        let mut human_response: String = String::new();
        stdin()
        .read_line(&mut human_response)
        .expect("Failed to read response");

        //Trim whitespace and convert to lowercase
        let human_response: String = human_response.trim().to_lowercase();

        //Match response
        match human_response.as_str() {
            "1" | "Ok" | "y" => return true,
            "2" | "no" | "n" => return false,
            _ => {
                println!("Invalid input. Please select '1' or '2'");
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn tests_print_agent_message() {
        PrintCommand::AICall.print_agent_message(
            "Managing Agent",
            "This is a test message for AICall from the Managing Agent.",
        );
    }
}
